Repository devsoc-unsw/circles, pull requests merged in 2022-09, with the labels that each got.

#693 Uzaif/cf 281
  frontend/src/pages/TermPlanner/SettingsMenu/SettingsMenu.tsx
  frontend/src/reducers/plannerSlice.ts
Labels: javascript

#699 Circles 342 why course locked
  backend/algorithms/objects/conditions.py
  backend/algorithms/tests/test_conditions.py
  backend/server/tests/planner/test_validate_term_planner.py
  frontend/src/pages/TermPlanner/DraggableCourse/DraggableCourse.tsx
  run_app.py
Labels: python

#779 chore(ci): add test reporting to ci
  .github/workflows/ci_BE.yml
  backend/.gitignore
  backend/requirements.txt
Labels: github_actions
